matrix:
  include:
  - language: node_js
    stage: "Web React"
    group: "stable"
    node_js:
      - "stable"
    cache:
      directories:
        - node_modules
    before_script: cd ./desafiosoftplan.web
    script:
      - npm install
      - npm test
      - npm run build

  - language: csharp
    stage: "Server Api"
    group: "stable"
    sudo: required
    dist: trusty
    env:
      - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true DOTNET_CLI_TELEMETRY_OPTOUT=true
    addons:
      apt:
        packages:
        - gettext
        - libcurl4-openssl-dev
        - libicu-dev
        - libssl-dev
        - libunwind8
        - zlib1g
    dotnet: 2.1.403
    mono: latest
    os:
      - linux
    branches:
      only:
        - master
    before_install:
      - chmod +x build.sh 
    script:
      - ./build.sh